name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@add_support_for_canonical_k8s
    secrets: inherit
    with:
      juju-channel: 3.3/stable
      provider: k8s
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
      use-canonical-k8s: true
