name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      channel: 1.28-strict/stable
      juju-channel: 3.4/stable
      self-hosted-runner: true
      self-hosted-runner-label: "edge"
