name: Publish to edge

on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  publish-to-edge:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    permissions:
      actions: read
      contents: write
    secrets: inherit
    with:
      channel: latest/edge
      integration-workflow-name: test.yaml
      working-directory: .
